export const charcoal = '#3D3D3D'
export const lightGrey = '#e6ecf0'
export const hoverSuperLightGrey = '#F7F9F9'
export const steelyBlue = '#4c5a66'
export const boxShadow = '#eee'
export const seaGreen = '#B0EDD2'
